added discord channel link
DSCVITBHOPAL/Portfolio-Generator pull request #6
Opened 2021-09-13 09:42 UTC by sibteali786

2021-09-13 10:07 UTC, basuabhirup approved these changes

2021-09-16 14:21 UTC, Akshit1311 requested changes
Looks good! Just add a line break before before the discord line set the target branch to **staging** instead of **main**
![image](https://user-images.githubusercontent.com/34763983/133628811-cebf311b-f9ed-420e-83d7-0d34ef2ad198.png)

2021-09-17 02:27 UTC, sibteali786 commented
Hey @Akshit1311 sorry to bother you but do you want to have extra line before discord link.

2021-10-02 12:09 UTC, Akshit1311 commented
Hey @sibteali786 I'm closing this pr as it has already been fixed, glad to see your enthusiasm you can browse other issues and ask to be assigned. Happy Hacking!

2021-10-02 12:09 UTC, closed without merging